backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img
# display_url: https://vianneysabourin.netlify.app/

collections:
  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "En", name: "en", widget: "markdown" }
      - { label: "Fr", name: "fr", widget: "markdown" }
